package:
  name: pims
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') + '_py' + environ['PY_VER'] }}

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - six
    - numpy
    - scikit-image  # one of { scikit-image | matplotlib }
    - tifffile

  run:
    - python
    - slicerator >=0.9.3
    - six >=1.8
    - numpy >=1.7
    - scikit-image  # one of { scikit-image | matplotlib }
    - tifffile >=0.3.1
    - pillow  # optional, but necessary for ipython rich display
    - pyav # [unix]

test:
  imports:
    - pims

about:
  home: http://soft-matter.github.io/pims
  license: 3-clause BSD License
  summary: 'Python Image Sequence: lazy-loading image I/O with fancy slicing'
